secrets:
  token:  # Discord token
  client_id: 1002789902557130792
  client_secret: 
  japi_key: # From https://key.japi.rest

redis_url: "redis://127.0.0.1:6379" # Redis URL

main_server: 789934742128558080

static: http://localhost:1010 # Change this in prod
sunbeam: http://localhost:5001 # Change this in prod

perms:
  sudo: 
    roles: 
      - 976891305336655903 # dev
      - 836326299223195738 # overseer
      - 999035725272068166 # owner
    index: 10
  head_admin:
    roles:
      - 836349482340843572 # head admin
    index: 9