secrets:
  token:  # Discord token
  client_id: 1031535884539023370
  client_secret: 
  japi_key: # From https://key.japi.rest

storage:
  postgres: # Postgres database
    host: # Hostname, defaults to PGHOST
    port: 5432 # Defaults to PGPORT
    user: # Defaults to PGUSERNAME
    password: # Defaults to PGPASSWORD
    database: fateslist # Must be provided
  redis:
    host: 127.0.0.1 # Hostname, defaults to REDIS_HOST
    port: 6379 # Defaults to REDIS_PORT
    password: # Defaults to REDIS_PASSWORD
    database: 0 # Defaults to REDIS_DB

main_server: 789934742128558080

static: http://localhost:1010 # Change this in prod
sunbeam: http://localhost:5001 # Change this in prod

perms:
  sudo: 
    roles: 
      - 976891305336655903 # dev
      - 836326299223195738 # overseer
      - 999035725272068166 # owner
    index: 10
  head_admin:
    roles:
      - 836349482340843572 # head admin
    index: 9

channels:
  bot_logs: 1030713957549342740

misc:
  restricted_vanity:
    - "api"
    = "docs"
    - "add-bot"
    - "admin"