name: Kitescratch Tests

on: [push]

env:
  NO_INTERACTION: "true"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          cp -rf config.sample.yaml config.yaml


      - name: Tests
        run: |
          cd kitescratch/kitehelper
          go build -v 
          ./kitehelper test