name: Kitescratch Tests

on: [push]

env:
  NO_INTERACTION: "true"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install nodejs dependencies
        run: |
          cd sunbeam
          npm ci

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          cp -rf config.sample.yaml config.yaml


      - name: Tests
        run: |
          cd kitescratch/kitehelper
          go build -v 
          ./kitehelper test
      
      - name: Push changes
        run: |
          git config --global user.name "Kitescratch Tests[bot]"
          git config --global user.email "kts+github-actions[bot]@users.noreply.github.com"
          git add -v .
          git commit -m "Kitescratch: Lint+Format task"
          git push
